// WordPress webpack config.
const defaultConfig = require('@wordpress/scripts/config/webpack.config');

// Plugins.
const RemoveEmptyScriptsPlugin = require('webpack-remove-empty-scripts');

// Utilities.
const path = require('path');

// Add any new entry points by extending the webpack config.
module.exports = {
  ...defaultConfig,
  ...{
    entry: {
      'js/editor': path.resolve(process.cwd(), 'assets/js', 'editor.js'),
      'js/scripts': path.resolve(process.cwd(), 'assets/js', 'scripts.js'),
      'css/editor': path.resolve(process.cwd(), 'assets/scss', 'editor.scss'),
      'css/styles': path.resolve(process.cwd(), 'assets/scss', 'styles.scss'),
    },
    plugins: [
      // Include WP's plugin config.
      ...defaultConfig.plugins,

      // Removes the empty `.js` files generated by webpack but
      // sets it after WP has generated its `*.asset.php` file.
      new RemoveEmptyScriptsPlugin({
        stage: RemoveEmptyScriptsPlugin.STAGE_AFTER_PROCESS_PLUGINS
      })
    ]
  }
};