const defaultConfig = require('@wordpress/scripts/config/webpack.config');
const RemoveEmptyScriptsPlugin = require('webpack-remove-empty-scripts');
const path = require('path');

module.exports = {
  ...defaultConfig,
  ...{
    entry: {
      'js/editor': path.resolve(process.cwd(), 'assets/js', 'editor.js'),
      'js/scripts': path.resolve(process.cwd(), 'assets/js', 'scripts.js'),
      'css/editor': path.resolve(process.cwd(), 'assets/css', 'editor.css'),
      'css/styles': path.resolve(process.cwd(), 'assets/css', 'styles.css'),
    },
    plugins: [
      ...defaultConfig.plugins,

      // Removes the empty `.js` files generated by webpack but sets it after WP has generated its `*.asset.php` file.
      new RemoveEmptyScriptsPlugin({
        stage: RemoveEmptyScriptsPlugin.STAGE_AFTER_PROCESS_PLUGINS
      })
    ]
  }
};
